### ISSUE TITLE
gpt-3.5-turbo 增加了两个新的模型，可以考虑增加模型选择列表

### ISSUE THREAD

**Issue by KennyLeung** [dirk1983/chatgpt#102]
昨天收到的openai的邮件，说增加了 gpt-3.5-turbo-0613 和 gpt-3.5-turbo-16k 两个模型。6月27日起，gpt-3.5-turbo 将会自动使用 gpt-3.5-turbo-0613 代替，原来的 gpt-3.5-turbo 变成 gpt-3.5-turbo-0301。

我试了 gpt-3.5-turbo-0613 和 gpt-3.5-turbo-16k，确实有所不同，gpt-3.5-turbo-0613对预置的提示词理解有误，比如 面试官 那条，gpt-3.5-turbo-0613把自己的角色理解成面试者。gpt-3.5-turbo-16k则仍保持正确理解。

**Comment by MingLiang66** [comment]
可以在setsession文件中手动改模型，如果想在界面显示选项，可以自己增加代码
