### ISSUE TITLE
win版本似乎，回答的时候限制了字数

### ISSUE THREAD

**Issue by wmgm183** [dirk1983/chatgpt#104]
问了几次似乎 后面都有没显示完成的字数
![image](https://github.com/dirk1983/chatgpt/assets/62553011/37ea1952-dee7-4afb-b51b-8c05d8ccdb8c)

![image](https://github.com/dirk1983/chatgpt/assets/62553011/f94fe304-3cd9-49a0-8d33-0ff316d72fbf)

**Comment by MingLiang66** [comment]
绘图是需要以“画”字开头的，代码里是识别“画”字调用不同分支的
