### ISSUE TITLE
填写完key运行报错：OpenAI服务器访问超时或未知类型错误

### ISSUE THREAD

**Issue by koulas** [dirk1983/chatgpt#110]
无法使用，报错
OpenAI服务器访问超时或未知类型错误

该key在旧版本是可以正常使用的，我现在还是在用旧版本的。

**Comment by jacob-du** [comment]
1. 可能是没有安装 `php7.x-curl` 模块
2. 没有权限： `sudo chwon -R www-data:www-data chatgpt/`

**Comment by jacob-du** [comment]
> 无法使用，报错 OpenAI服务器访问超时或未知类型错误
> 
> 该key在旧版本是可以正常使用的，我现在还是在用旧版本的。

1. 可能是没有安装 `php7.x-curl` 模块
2. 或者是没有权限： `sudo chown -R www-data:www-data chatgpt/`

**Comment by PURE281** [comment]
win上部署openkey没问题,php使用5.6版本.也出现了这个异常,求解答

**Comment by dirk1983** [comment]
F12看看具体错误

**Comment by guotao** [comment]
新加坡服务器上搭了一个demo ，供有需要的童鞋 https://game.jielun.fun/chat/?gh
