### ISSUE TITLE
一直卡在‘正在组织语言，请稍等片刻...’

### ISSUE THREAD

**Issue by suyc0707** [dirk1983/chatgpt#116]
我直接在phpstorm克隆下来，更改自己的key后就这样，php8.1

**Comment by guxin0123** [comment]
install php-mbstring php-curl

**Comment by suyc0707** [comment]
非常感谢

**Comment by LonelyTaoist** [comment]
我install了之后还是卡在这一步

**Comment by guotao** [comment]
https://game.jielun.fun/chat/?f=gith 我的也可以了。谢谢。
