### ISSUE TITLE
能不能添加支持本地模型的选项，比如ollama

### ISSUE THREAD

**Issue by qdylanq** [dirk1983/chatgpt#121]
Hi
能不能添加支持本地模型的选项，比如ollama下面的本地模型

**Comment by dirk1983** [comment]
你可以写个转换程序接口，把ollama的格式转换成标准的openai接口规范，就可以调用了

**Comment by dirk1983** [comment]
你可以写个转换程序接口，把ollama的格式转换成标准的openai接口规范，就可以调用了
