### ISSUE TITLE
如何切换至自定义key? 取消index注释后, 显示API-Key无效

### ISSUE THREAD

**Issue by terobox** [dirk1983/chatgpt#17]
自定义key功能无法使用, 取消掉index注释后, 程序仍然调用stream中系统的key

**Comment by aimiku** [comment]
stream.php 里面将
7 //if ((isset($_SESSION['key'])) && (!empty($_POST['key']))) {
8 //    $OPENAI_API_KEY = $_SESSION['key'];
9 //}
注释掉就好了

**Comment by dirk1983** [comment]
最新版应该没有bug了才对，其他人有这个问题吗？

**Comment by kuaiyun33** [comment]
缺少一个功能，代码部分增加一键复制按钮。

**Comment by kuaiyun33** [comment]
还缺少角色功能，建议增加

**Comment by Zoumachuan** [comment]
> 最新版应该没有bug了才对，其他人有这个问题吗？

这个bug依旧存在
