### ISSUE TITLE
OpenAI服务器访问超时

### ISSUE THREAD

**Issue by TS1989ED** [dirk1983/chatgpt#21]
修改了CURLOPT_PROXY那一行使用了本地代理，但是每次点击立马都会提示“OpenAI服务器访问超时”，APIKey也用的是自己的。

**Comment by JerryliDe** [comment]
一样的问题，我查了返回下实际上是openai报了错误消息，说json body不对。也很费解。json是对的啊
errmsg={
"error": {
"message": "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please send an email to [support@openai.com](mailto:support@openai.com) and include any relevant code you'd like help with.)",
"type": "invalid_request_error",
"param": null,
"code": null
}
}

**Comment by JerryliDe** [comment]
我找到问题了， 是php的session目录没有权限，俩php内自己重指定一个有权限的目录即可。

**Comment by dirk1983** [comment]
> 修改了CURLOPT_PROXY那一行使用了本地代理，但是每次点击立马都会提示“OpenAI服务器访问超时”，APIKey也用的是自己的。

估计是你的代理配置有问题，必须是http代理，并且要注意IP和端口。提示超时就是访问不到，和APIKEY没关系

**Comment by JerryliDe** [comment]
> > 修改了CURLOPT_PROXY那一行使用了本地代理，但是每次点击立马都会提示“OpenAI服务器访问超时”，APIKey也用的是自己的。
> 
> 估计是你的代理配置有问题，必须是http代理，并且要注意IP和端口。提示超时就是访问不到，和APIKEY没关系

提示超时也可能是error msg无法识别。比如"type": "invalid_request_error", 无效的请求。此时需要打印出$postData看看是啥东西，或者把php的报错打开，看看错误原因。我当时的情况就是这样最后是发现session目录写不进去。给好权限就解决了。

**Comment by wmgm183** [comment]
> php的session

宝塔php的session路径在哪里？
