### ISSUE TITLE
What is "Continuous conversations" ?

### ISSUE THREAD

**Issue by oleteacher** [dirk1983/chatgpt#22]
Question: what is the "Continuous conversations" function?

`<input type="checkbox" id="keep" checked="" style="min-width:220px;">`

Changing the state has no effect that I can see. Have students asking and not positive what I should tell them.

Sorry if not the place to ask questions, but in school we cannot join your wechat group.

Thank you for your time.

**Comment by sahuidhsu** [comment]
Basically it turns on the contextual analysis of the chat flow.
When it's enabled, AI will consider previous questions and answers when generating new answer.

**Comment by oleteacher** [comment]
@sahuidhsu Thank you, explained perfectly!
