### ISSUE TITLE
大哥我就问一句你啥时候能把api-key不合法解决了，咋更新都有一直有这个问题，

### ISSUE THREAD

**Issue by jasonpan168** [dirk1983/chatgpt#23]
![微信截图_20230307090053](https://user-images.githubusercontent.com/104338733/223298556-9986c2d2-96e2-4a33-9173-c0efca59f8e7.png)

**Comment by JerryliDe** [comment]
应该确实是不合法，你得去重新生成个key。或者openai阻止了你的访问

**Comment by dirk1983** [comment]
最新版本应该是正常运行的，你再重新下载解压，在stream.php里面填上你的合法APIKEY试试。APIKEY最好再去openai.com上确认一下是否还有效，有时可能会被官方删除。
