### ISSUE TITLE
目前遇到的两个bug

### ISSUE THREAD

**Issue by Zoumachuan** [dirk1983/chatgpt#36]
1.有关apikey的使用
目前遇到以下问题，当stream.php中给出正确的apikey，而在前端给出无论正确与否的apikey时，仍能正常运行，然而当在stream.php中给出错误的或无效的apikey时，前端就算给出正确的apikey也无法运行，猜测是和优先运行度有关。
2.有关chat.txt的写入
我是用的是腾讯云+ubuntu宝塔面板，在服务器上部署了所有文件后直接通过宝塔将域名接入，在此情况下，chat.txt无法正确的写入，请问可能是什么原因造成的？

**Comment by dirk1983** [comment]
问题1是个bug，已解决。
问题2是文件权限问题，要有写权限。
