### ISSUE TITLE
Your openAI secret key is published

### ISSUE THREAD

**Issue by oelmekki** [dirk1983/chatgpt#38]
Hi,

Just a fair warning that you've published your API key:

https://github.com/dirk1983/chatgpt/blob/3fe554bcebbc71d207cef9af33f63c7994dffee3/stream.php#L8

 If you have a a paying account on openAI's api and this key is still valid, it may be used to access the api while billing you. You should probably deactivate this key in openAI's dashboard and remove it from your code, using instead an environment variable or similar.

**Comment by dirk1983** [comment]
Thank you for your kind reminder.
