### ISSUE TITLE
连续对话Issue

### ISSUE THREAD

**Issue by 2003pro** [dirk1983/chatgpt#4]
我尝试了使用连续对话，但是多轮后出现json error
![image](https://user-images.githubusercontent.com/13690816/222503663-d6f33c52-f90d-42bf-9698-d330a1682941.png)

**Comment by ImCharcher** [comment]
Yes i can confirm the last update you made dont fix the json issue.

**Comment by 2003pro** [comment]
> Yes i can confirm the last update you made dont fix the json issue.

Yep. I also checked the latest commit and applied it. But the json decode issue still exists.

**Comment by 2003pro** [comment]
This public commit actually solved this issue. 
https://github.com/dirk1983/chatgpt/pull/6#issue-1607845731
