### ISSUE TITLE
没有代码高亮功能了？

### ISSUE THREAD

**Issue by yikaiba** [dirk1983/chatgpt#40]
![image](https://user-images.githubusercontent.com/19700380/224522030-e8f91d42-7a13-476d-9ae8-f8a070b469d2.png)

**Comment by dirk1983** [comment]
openai返回的代码不是markdown格式的就不会对代码进行着色。你可以跟AI说“用markdown格式写一段代码”。其实多数情况下openai接口返回的代码都是markdown格式的，偶尔是纯文本格式。
