### ISSUE TITLE
代码格式化输出的bug

### ISSUE THREAD

**Issue by Basicconstruction** [dirk1983/chatgpt#46]
![image](https://user-images.githubusercontent.com/66370519/225212885-ac9e0314-40ae-4e67-8d1d-8d1793495704.png)
![image](https://user-images.githubusercontent.com/66370519/225212990-810be91c-0f16-4583-8ac2-f10642bea983.png)
查看日志可以发现，或许是markdown的原因使得在识别C/C++的include时，会出现更大的一行，而不是符合预期的转化为代码块的显示形式。

**Comment by dirk1983** [comment]
最新版本已解决该问题
