### ISSUE TITLE
偶尔会丢失单词

### ISSUE THREAD

**Issue by gdmec07150942** [dirk1983/chatgpt#47]
![image](https://user-images.githubusercontent.com/22065379/225230952-0e93a3ca-b5d9-4716-a160-9c0c081533bf.png)
第一句返回的就是"," ，逗号，前面应该有there!
![image](https://user-images.githubusercontent.com/22065379/225231134-c6b5da9b-6185-4386-b294-b77c2f14eaa8.png)

最后打印出来的结果，确实也是少了，有人遇到过这个情况吗？

**Comment by gdmec07150942** [comment]
@dirk1983 作者大大，有遇到过吗？我本地直接经常复现

**Comment by dirk1983** [comment]
从你抓包的情况来看应该是openai官方接口返回数据的问题，或者是你本地网络丢包造成的。
