### ISSUE TITLE
OpenAI服务器访问超时或未知类型错误

### ISSUE THREAD

**Issue by ymxdppz** [dirk1983/chatgpt#48]
部署到线上就显示“OpenAI服务器访问超时或未知类型错误”
使用的docker部署
部署方式和本地完全一致，但是本地运行正常，线上服务器就会失败

**Comment by guotao** [comment]
是不是网卡驱动错了，  我的demo可以 https://game.jielun.fun/chat/?g_h

**Comment by dirk1983** [comment]
注意文件权限问题，另外也有网友反馈是PHP版本问题

**Comment by lp123sun** [comment]
> 

centos7.9默认的php5.4不行，也是这个提示，升级带php7.4后可以了

**Comment by gae** [comment]
vps centos7.9 php7.4，同样的问题

**Comment by lp123sun** [comment]
> vps centos7.9 php7.4，同样的问题

查看nginx的日志吧：
例如： FastCGI sent in stderr: "PHP message: PHP Warning:  session_start(): open(/var/lib/php/session/sess_****, O_RDWR) failed: Permission denied (13) in 

添加权限：
chown -vR nginx:nginx /var/lib/php
