### ISSUE TITLE
关于跨域的问题

### ISSUE THREAD

**Issue by yhnoxn** [dirk1983/chatgpt#5]
大佬，能写一下跨域相关的教程么(chat.js)

**Comment by dirk1983** [comment]
message.php最新代码已经支持跨域访问了。你可以把所有代码部署到国外服务器，直接访问国外网站即可。如果原来的网站在国内，可以先修改chat.js跳转的网址临时解决（搜索message.php，把他前面加上http://你的国外服务器域名/message.php即可）。国外服务器也要有php环境，把整个项目传上去，注意文件权限。
