### ISSUE TITLE
Debugger message

### ISSUE THREAD

**Issue by oleteacher** [dirk1983/chatgpt#51]
The school firewall (according to IT department) is triggering on Chinese character in this:

![image](https://user-images.githubusercontent.com/26278259/225613571-05fff5b0-c384-459c-993a-d7eb2f1cf636.png)

Where can I find this in code?

I have never had to deal with this type of issue and our IT department is less than helpful :(

Thanks!

**Comment by dirk1983** [comment]
you can delete function init() in js/chat.js

**Comment by oleteacher** [comment]
Thank you. IT department removed all scripts from intranet and we can no longer use. Will see if this helps get back online for the kids.

**Comment by oleteacher** [comment]
Unfortunately I see no `function init()` in chat.js.

**Comment by oleteacher** [comment]
Please, can you help me with this issue?

**Comment by oleteacher** [comment]
I ask again, please help me solve this issue. The kids were using this wonderful chatgpt in classroom and loving it. They can no longer use.

Our IT department is not helpful in changing code, I have to make changes to code and resubmit.

Please explain how to remove the debugging message.

**Comment by oleteacher** [comment]
Thank you thank you @<retracted> for getting me back inline.
