### ISSUE TITLE
advise:preset-text can be set to system message?

### ISSUE THREAD

**Issue by jwsky** [dirk1983/chatgpt#54]
an advise to discuss:
The preset text is currently set in the user role. However, if it were set in the system role, the experience would be improved as you wouldn’t have to worry about the five round restrictions .And  it's hidden in the background ,this should better.

**Comment by dirk1983** [comment]
You are quite right. I knew it would be better to do so, but I was a little bit lazy to do so. Hope someone make a PR to realize it.
