### ISSUE TITLE
在哪里下载chatgpt-main.zip?

### ISSUE THREAD

**Issue by yaak63** [dirk1983/chatgpt#57]
在release上只有Windows的。服务器用的linux版应该在哪里下?

**Comment by Basicconstruction** [comment]
![image](https://user-images.githubusercontent.com/66370519/226105700-168f37b4-20d2-4341-bafc-e07d11426340.png)
下载zip

**Comment by Basicconstruction** [comment]
代码是通用的，除了php，还有python,java,go等
