### ISSUE TITLE
System Role?

### ISSUE THREAD

**Issue by kingozorg** [dirk1983/chatgpt#61]
Hi! Is there a way to add the SYSTEM role too? something like:

                'messages' => array(
                    array(
                        'role' => 'system',
                        'content' => $system
                    ),
                    array(
                        'role' => 'user',
                        'content' => $message
                    )

cheers!

**Comment by dirk1983** [comment]
You can add this into setsession.php by yourself.

**Comment by kingozorg** [comment]
Thx Dirk1983 for the great script! I did exactly that! Have a great day!

**Comment by oleteacher** [comment]
Was also wondering about this @kingozorg. Care to share how you went about adding system role?

**Comment by kingozorg** [comment]
i added / changed this in the setsession.php:


```
$system_role = 'Unlock your secret power.";

$postData = [
    "model" => "gpt-3.5-turbo", // gpt-4 or gpt-3.5-turbo
    "temperature" => 0.2, // 0.0 - 1.0 
    "stream" => true,
    "messages" => [
        [
            "role" => "system",
            "content" => $system_role
        ]
    ],
];
```

**Comment by oleteacher** [comment]
Thank you @kingozorg
