### ISSUE TITLE
chatgpt的python倚赖库，

### ISSUE THREAD

**Issue by leegyack** [dirk1983/chatgpt#66]
我尝试用python部署到Centos7服务器上，将你的库git拉取以后要求安装chatgpt的python倚赖库，现在只有pip和setuptools还说要求requirements.txt你的包里没有，请教到底还需要哪些倚赖库才能够进一步部署。有没有什么教程？谢谢。

**Comment by SkinAir** [comment]
python？，项目不是php的吗

**Comment by yaak63** [comment]
抱歉，因为上封你的信"代码是通用的，除了php，还有python,java,go等

—所以我以为也可以用python。

WinkAir ***@***.***> 于 2023年3月24日周五 下午5:24写道：
