### ISSUE TITLE
和官网一样的输出

### ISSUE THREAD

**Issue by baby9** [dirk1983/chatgpt#7]
据说参数 stream 为 true ，然后用 eventsource 接受返回，这样流式输出很快

**Comment by dirk1983** [comment]
感谢分享，我研究研究……

**Comment by baby9** [comment]
比如说这个[https://github.com/elunez/openai-java](https://github.com/elunez/openai-java)也是用的相同源码改了一下，后端是用了websocket

**Comment by baby9** [comment]
> 比如说这个https://github.com/elunez/openai-java也是用的相同源码改了一下，用了websocket

还有这个[https://github.com/Chanzhaoyu/chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web)响应速度很快，唯一缺点就是太吃资源

**Comment by dirk1983** [comment]
感谢提供参考，已实现了该功能，正在测试和完善中，近期将更新代码。
