### ISSUE TITLE
setsession.php -nginx 502/504 timeout

### ISSUE THREAD

**Issue by SkinAir** [dirk1983/chatgpt#70]
![399beeb1f0c86c4fdb7dbb0e7f14d25](https://user-images.githubusercontent.com/71880910/227478964-cb50a9e3-0a45-48eb-bb59-7ca621137df3.png)

**Comment by dayantrivani** [comment]
我遇到500错误，你可参考。
https://github.com/hsmbs/chatgpt-php这个项目
看nginx的error log，它打的docker缺乏一些php包

**Comment by SkinAir** [comment]
> 我遇到500错误，你可参考。 https://github.com/hsmbs/chatgpt-php 这个项目 看nginx的error log，它打的docker缺乏一些php包

我知道他有问题，所以我用的是gindex/nginx-php的镜像，自己搭的，errorlog如下
![1679882668868](https://user-images.githubusercontent.com/71880910/227823427-396a6444-17ac-4f41-ac51-8bb4f5273228.jpg)
