### ISSUE TITLE
不懂就问

### ISSUE THREAD

**Issue by husangou** [dirk1983/chatgpt#77]
买了点api结果发现那个api只支持定制的API地址，我去改了stream.php的api地址结果提示请输入正确的API-KEY我看了其他文件，没找到还需要改那些地方

**Comment by husangou** [comment]
![image](https://user-images.githubusercontent.com/79092733/230784974-2f91ebf1-dbb4-426a-867d-ea55f6ae362c.png)

**Comment by husangou** [comment]
https://ai.gpt.wf/forum.php?mod=viewthread&tid=22&extra=page%3D1

**Comment by a1464934451** [comment]
因为这个key不是官方的key 是别人自定义生成的key

**Comment by dirk1983** [comment]
是的，这个是别人搭的反代，无法实现流式效果，尽量不要用
